services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Активируем профиль Spring (по умолчанию dev, если не задано)
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE:-dev}
      # Эти переменные будут подставлены в application-prod.properties
      PROD_DB_URL: ${PROD_DB_URL}
      PROD_DB_USER: ${PROD_DB_USER}
      PROD_DB_PASS: ${PROD_DB_PASS}
      # Можно также переопределить URL, если не хотим использовать файлы
      # SPRING_DATASOURCE_URL: ${PROD_DB_URL}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      PPOSTGRES_DB: ${POSTGRES_DB:-chronomind}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - G:/Docker/DateBase/Postgres/16/docker:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-chronomind}"]
      interval: 10s
      timeout: 5s
      retries: 5