spring.application.name=ChronoMind

server.port=8080

server.servlet.context-path=/

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true

#DataBase
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=

# Hikari Connection Pool
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5